# Kitty keybindings
kitty_mod ctrl+shift

# Tabs
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9

map kitty_mod+] move_tab_forward
map kitty_mod+[ move_tab_backward

# Panes (Kitty calls a pane a 'window')
map kitty_mod+enter new_window_with_cwd
map ctrl+alt+left neighboring_window left
map ctrl+alt+right neighboring_window right
map ctrl+alt+up neighboring_window up
map ctrl+alt+down neighboring_window down

map kitty_mod+q close_window
map kitty_mod+w detach_window new-tab

# Scrolling
map kitty_mod+home scroll_to_prompt -1
map kitty_mod+end scroll_to_prompt 1

# Misc
map kitty_mod+delete clear_terminal to_cursor_scroll active
map ctrl+shift+grave kitty_shell window
map kitty_mod+space command_palette
map ctrl+shift+/ open_url https://sw.kovidgoyal.net/kitty/

map kitty_mod+0 change_font_size all 0

# Mouse Actions
mouse_map left click ungrabbed mouse_handle_click selection prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click selection link prompt
mouse_map ctrl+left press ungrabbed mouse_selection drag_or_normal_select

# Don't intercept the following key strokes
map ctrl+shift+z no_op
map ctrl+shift+x no_op
map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+esc no_op
map kitty_mod+c copy_or_noop

# Disable opacity binds because I don't have dynamic opacity on
map ctrl+shift+a no_op
#map ctrl+shift+a>1 no_op
#map ctrl+shift+a>d no_op
#map ctrl+shift+a>l no_op
#map ctrl+shift+a>m no_op
