# Kitty Config file
# Lots more options avalable than exist in this file
# see all config options here: https://sw.kovidgoyal.net/kitty/conf/#

enable_audio_bell yes
visual_bell_duration 0.6

# Scrollback
scrollback_lines 9000
scrollback_pager_history_size 10
scrollback_pager moor

# Tabs
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
bell_on_tab " "
tab_title_template "{fmt.fg.magenta}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}{tab.progress_percent}"

# Layout
# all layouts enabled, custom order for layout cycling
enabled_layouts splits:split_axis=auto,tall,fat,grid,horizontal,vertical,stack 

# Colour // Style
background_opacity 0.60
text_fg_override_threshold 0 ratio
background_blur 0

# Cursor
cursor_shape beam
cursor_beam_thickness 2
cursor_stop_blinking_after 5.0

# Misc
confirm_os_window_close 0
touch_scroll_multiplier 5.0
show_hyperlink_targets no

# Key Bindings & Mouse
kitty_mod ctrl+shift

map kitty_mod+q close_window
map kitty_mod+w detach_window new-tab

map kitty_mod+delete clear_terminal to_cursor_scroll active

map kitty_mod+home scroll_to_prompt -1
map kitty_mod+end scroll_to_prompt 1

map kitty_mod+0 change_font_size all 0

map ctrl+shift+grave kitty_shell window

mouse_map left click ungrabbed mouse_handle_click selection prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click selection link prompt

# Don't intercept the following key strokes
map ctrl+shift+z no_op
map ctrl+shift+x no_op
map ctrl+shift+left no_op
map ctrl+shift+right no_op
# map ctrl+shift+/ no_op 
map ctrl+shift+/ open_url https://sw.kovidgoyal.net/kitty/
map kitty_mod+c copy_or_noop

# Environment
shell zsh
editor edit
# Enable private use area chars in less (Nerd fonts)
env LESSUTFCHARDEF=E000-F8FF:p,F0000-FFFFD:p,100000-10FFFD:p
# Make sure editor is set even when running TUIs from desktop files
env EDITOR=edit

# shell_integration enabled
# shell_integration is broken when a global zshenv exists (Im using it to set $ZDOTDIR) 
# so shell_integration has to be set up manually
shell_integration no-rc

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size 13.0
disable_ligatures cursor

# BEGIN_KITTY_THEME
# VSCode_Dark
include current-theme.conf
# END_KITTY_THEME
