# Kitty Config file
# Lots more options avalable than exist in this file
# see all config options here: https://sw.kovidgoyal.net/kitty/conf/#

enable_audio_bell yes
visual_bell_duration 0.6
window_alert_on_bell yes

# BEGIN_KITTY_THEME
# VSCode_Dark
include current-theme.conf
# END_KITTY_THEME

# Scrollback
scrollback_lines 9000
scrollback_pager_history_size 10
scrollback_pager moor -no-linenumbers +INPUT_LINE_NUMBER

# Tabs
tab_bar_edge top
tab_bar_margin_height     3 0
tab_bar_style             separator
tab_separator             ""
tab_bar_min_tabs          2
bell_on_tab " "

# Tab bar colors
# active_tab_foreground   #ffffff
# active_tab_background   #3a3d41
# inactive_tab_foreground #858485
# inactive_tab_background #1e1e1e

tab_title_template        "{fmt.fg.color0}{fmt.bg.default} {fmt.bg.tab}{fmt.fg._fca17d}{bell_symbol}{activity_symbol}{fmt.fg.tab} {title} {tab.progress_percent}{fmt.fg.color0}{fmt.bg.default}"
active_tab_title_template "{fmt.fg._38384d}{fmt.bg.default} {fmt.bg.tab}{fmt.fg._fca17d}{bell_symbol}{activity_symbol}{fmt.fg.tab} {title} {fmt.fg._38384d}{fmt.bg.default}"

# Layout
# all layouts enabled, custom order for layout cycling
enabled_layouts splits:split_axis=auto,fat,tall,grid,horizontal,vertical,stack 
focus_follows_mouse drop

# Colour // Style
background_opacity 0.60
text_fg_override_threshold 0 ratio
background_blur 0
window_padding_width 2
progress_bar bottom

# Cursor
cursor_shape beam
cursor_beam_thickness 2
cursor_stop_blinking_after 5.0

# Misc
confirm_os_window_close 0
touch_scroll_multiplier 5.0
show_hyperlink_targets ctrl

# Key Bindings & Mouse
include keybinds.conf

# Environment
shell zsh
editor edit
# Enable private use area chars in less (Nerd fonts)
env LESSUTFCHARDEF=E000-F8FF:p,F0000-FFFFD:p,100000-10FFFD:p
# Make sure editor is set even when running TUIs from desktop files
env EDITOR=edit

# shell_integration enabled
# shell_integration is broken when a global zshenv exists (Im using it to set $ZDOTDIR) 
# so shell_integration has to be set up manually
shell_integration no-rc

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size 13.0
disable_ligatures cursor
