# https://sw.kovidgoyal.net/kitty/open_actions/
# !!! Mime types are determined by extention NOT magic

# Open directories in yazi
protocol file
mime inode/directory
# action send_text all cd $FILE_PATH\r
action launch --location hsplit --cwd ${FILE_PATH} yazi

# Open man pages
protocol man
action launch --location vsplit man ${FILE_PATH}

protocol kitty+doc
action show_kitty_doc $URL_PATH

# Open URLs in the browser
protocol http, https
action launch --type=background xdg-open ${URL}

protocol file
mime application/pdf
action launch --type=background xdg-open ${FILE_PATH}

# Open any image in the full kitty window by clicking on it
protocol file
mime image/*
action launch --type=overlay kitten icat --hold -- ${FILE_PATH}

# Open media in VLC
protocol file
mime video/*
action launch --type=background env -u DISPLAY vlc ${URL}

protocol file
mime audio/*
action launch --type=background env -u DISPLAY vlc ${URL}

# Open text in editor
protocol file
mime text/*
action launch ${EDITOR} ${FILE_PATH}

# .files that kitty can't identify as text, but we know are text
protocol file
ext bashrc, bash_profile, bash_logout, zshrc, zshenv, zprofile, gitignore
action launch ${EDITOR} ${FILE_PATH}
