# SSH kitten configuration
# https://sw.kovidgoyal.net/kitty/kittens/ssh/

hostname sky@*

env EDITOR=kitten edit-in-kitty
copy --symlink-strategy keep-path .bashrc
copy --symlink-strategy keep-path .config/starship.toml

shell_integration enabled