# SSH kitten configuration
# https://sw.kovidgoyal.net/kitty/kittens/ssh/

# Server
hostname sky@violence

env EDITOR=kitten edit-in-kitty
copy --symlink-strategy keep-path .bashrc
copy --symlink-strategy keep-path .config/starship.toml
shell_integration enabled

# NAS
hostname sky@archives

env EDITOR=kitten edit-in-kitty
copy --symlink-strategy keep-path .bashrc
copy --symlink-strategy keep-path .config/starship.toml
shell_integration enabled

# Kobo Libre Colour
hostname kobo

env EDITOR=kitten edit-in-kitty
shell_integration enabled

# Arch Installer
hostname archiso

env EDITOR=kitten edit-in-kitty
copy --symlink-strategy keep-path .bashrc
copy --symlink-strategy keep-path .bash_profile
copy --symlink-strategy keep-path .config/starship.toml
shell_integration enabled
