"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[[plugin.prepend_preloaders]]
mime = "{audio,video,image}/*"
run = "mediainfo"

[[plugin.prepend_previewers]]
mime = "{audio,video,image}/*"
run = "mediainfo"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url = "*/"
run  = "git"

[opener]
bulk-rename = [
    { run = "kitty kitten edit-in-kitty %s", block = true, for = "linux" },
    { run = "edit.exe %s", block = true, for = "windows" },
]
edit = [
    { run = "${EDITOR:-nano} %s", desc = "Edit", block = true, for = "unix" },
    { run = "%EDITOR% %s", desc = "Edit", block = true, for = "windows" },
]
code = [
    { run = "code %s", desc = "Code", for = "windows", orphan = true },
    { run = "zeditor %s", desc = "Zed", for = "linux", orphan = true },
]
view-bat = [
    { run = "bat --color=always --paging=always --italic-text=always --pager=less -- %s", desc = "Preview (bat)", block = true, for = "linux" },
]
view-image = [
    { run = "kitty kitten icat --hold -- %s", desc = "Preview (icat)", block = false, for = "linux" },
]

[open]
prepend_rules = [
    { url = "bulk-rename.txt", use = "bulk-rename" },
    { url = "*/", use = [ "reveal", "code" ] },
    { mime = "image/*", use = [ "view-image", "open", "reveal" ] },
    { mime = "text/*", use = [ "edit", "view-bat", "reveal" ] },
    { mime = "application/{json,ndjson,javascript,wine-extension-ini}", use = [ "edit", "view-bat", "reveal" ] },
]
append_rules = [
    { url = "*", use = [ "open", "edit", "code", "reveal" ] },
]
