name = "system"
name_pretty = "System Commands"
icon = "laptop"
global_search = true
search_name = true

[[entries]]
text = "Restart Open Tablet Driver"
subtext = "systemctl --user restart opentabletdriver.service"
keywords = ["tablet", "driver"]
icon = "/usr/share/pixmaps/otd.png"
actions = { "restart" = "systemctl --user restart opentabletdriver.service" }

[[entries]]
text = "Restart Elephant"
subtext = "systemctl --user restart elephant.service"
keywords = ["elephant"]
icon = "reload"
actions = { "restart" = "systemctl --user restart elephant.service" }

[[entries]]
text = "Color Picker"
subtext = "hyprpicker"
keywords = ["color", "picker", "hypr"]
icon = "color-picker"
actions = { "use" = "sleep 0.5 && hyprpicker -a" }
