always_show_default = true
command = 'xdg-open'
engines_as_actions = false
history = true
history_when_empty = false
text_prefix = 'Search: '

[Config]
hide_from_providerlist = false
icon = 'applications-internet'
min_score = 20
name_pretty = ''

[[entries]]
default = true
icon = ''
name = 'Google Search'
prefix = 'g '
url = 'https://www.google.com/search?q=%TERM%'

[[entries]]
default = false
icon = 'stock_addressbook'
name = 'Arch Wiki'
prefix = 'a '
url = 'https://wiki.archlinux.org/index.php?search=%TERM%'

[[entries]]
default = false
icon = 'github-desktop'
name = 'GitHub'
prefix = 'gh '
url = 'https://github.com/search?q=%TERM%&type=repositories'

[[entries]]
default = false
icon = 'preferences-desktop-search'
name = 'Wikipedia'
prefix = 'w '
url = 'https://en.wikipedia.org/w/index.php?search=%TERM%'
